accessControl:
  enabled: true
api:
  allowCrossOrigin: true
  key: 1D8DF67AD9594E81A44830CF33936F55
plugins:
  announcements:
    channels:
      _important:
        read_until: 1478614200
  discovery:
    upnpUuid: 452f54a5-65e9-4251-918d-578923a26612
serial:
  autoconnect: true
  baudrate: 0
  port: AUTO
server:
  firstRun: true
  seenWizards:
    corewizard: null
    cura: true
    softwareupdate: null
